sudo: required
services:
  - docker

before_install:
  - docker build -t raintech/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true raintech/react-test npm test

after_success:
  - docker build -t raintech/multi-react ./client
  - docker build -t raintech/multi-nginx ./nginx
  - docker build -t raintech/multi-server ./server
  - docker build -t raintech/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and put them to docker hub
  - docker push raintech/multi-react
  - docker push raintech/multi-nginx
  - docker push raintech/multi-server
  - docker push raintech/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-1'
  app: 'rt-multi-docker'
  env: 'Rt-multi-docker-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-1-371993076347'
  bucket_path: 'rt-multi-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
